from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from ._example_collect import SkippedExample, TypstExample, collect_typst_examples
except ImportError:  # pragma: no cover - supports direct script execution.
    from _example_collect import SkippedExample, TypstExample, collect_typst_examples


HEADER = """// Generated by scripts/generate_typst_fixture.py.
// Do not edit manually.
// Source: docstring Examples from typstpy registered functions.
"""

STATEMENT_PREFIXES = ('#import ', '#set ', '#show')
DIRECT_CALL_PREFIXES = (
    '#pagebreak(',
    '#linebreak(',
    '#parbreak(',
    '#colbreak(',
    '#bibliography(',
)
SKIP_TYPST_PREFIXES = ('#cite(', '#ref(', '#subpar.')


def should_skip_typst(example: TypstExample) -> str | None:
    """Return a skip reason if the snippet is not suitable for the fixture."""
    if example.qualname.startswith('subpar.'):
        return 'requires external Typst package'
    if example.typst.startswith(SKIP_TYPST_PREFIXES):
        return 'requires document context or external package'
    return None


def render_typst_example(number: int, example: TypstExample) -> str:
    """Render one collected Typst snippet into fixture source."""
    comment = f'// {example.qualname} example {example.index}'
    typst = example.typst
    if typst.startswith(STATEMENT_PREFIXES) or typst.startswith(DIRECT_CALL_PREFIXES):
        return f'{comment}\n{typst}\n'
    return f'{comment}\n#let example_{number:04d} = {typst[1:]}\n'


def build_fixture() -> tuple[str, list[SkippedExample]]:
    """Build the Typst fixture source and return skipped example metadata."""
    collected, skipped = collect_typst_examples()
    lines = [HEADER]
    fixture_index = 1

    for example in collected:
        reason = should_skip_typst(example)
        if reason is not None:
            skipped.append(
                SkippedExample(example.qualname, example.index, example.source, reason)
            )
            continue
        lines.append(render_typst_example(fixture_index, example))
        fixture_index += 1

    return '\n'.join(lines), skipped


def main(argv: list[str] | None = None) -> int:
    """Generate a Typst fixture from registered function doctests."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--write',
        type=Path,
        help='Write generated fixture to this path. Defaults to stdout.',
    )
    parser.add_argument(
        '--summary',
        action='store_true',
        help='Print a skipped-example summary to stderr.',
    )
    args = parser.parse_args(argv)

    content, skipped = build_fixture()
    if args.write is None:
        sys.stdout.write(content)
        if content and not content.endswith('\n'):
            sys.stdout.write('\n')
    else:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(content, encoding='utf-8')

    if args.summary:
        print(f'Skipped examples: {len(skipped)}', file=sys.stderr)
        for item in skipped:
            print(f'- {item.qualname}[{item.index}]: {item.reason}', file=sys.stderr)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
